{% set version = "2.0.4" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/p/pyhamcrest/pyhamcrest-{{ version }}.tar.gz
  sha256: b5d9ce6b977696286cf232ce2adf8969b4d0b045975b0936ac9005e84e67e9c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - hatchling
    - hatch-vcs
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - pytest-sugar
    - pytest-xdist
  imports:
    - hamcrest
  commands:
    - pip check
    - pytest -vv --cov=hamcrest --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=95

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Hamcrest framework for matcher objects

extra:
  recipe-maintainers:
    - duncanwp
    - stuertz
