{% set version = "2.1.0" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/p/pyhamcrest/pyhamcrest-{{ version }}.tar.gz
  sha256: c6acbec0923d0cb7e72c22af1926f3e7c97b8e8d69fc7498eabacaf7c975bd9c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - hatchling
    - hatch-vcs
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - pytest-sugar
    - pytest-xdist
    - python {{ python_min }}
  imports:
    - hamcrest
  commands:
    - pip check
    - pytest -vv --cov=hamcrest --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=95

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Hamcrest framework for matcher objects

extra:
  recipe-maintainers:
    - duncanwp
    - stuertz
