{% set version = "2.0.2" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  fn: PyHamcrest-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-{{ version }}.tar.gz
  md5: 7a086f0b067f8d38958ec32f054559b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools

  run:
    - python >=3.5

test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Hamcrest framework for matcher objects

extra:
  recipe-maintainers:
    - duncanwp
    - stuertz
